export const services = [
  {
    id: "makeup",
    category: "Makeup",
    description: "From natural glam to editorial looks, our artists craft the perfect canvas.",
    icon: "✦",
    items: [
      { name: "Bridal Makeup", price: 350, duration: 120 },
      { name: "Editorial Look", price: 220, duration: 90 },
      { name: "Natural Glow", price: 150, duration: 60 },
      { name: "Evening Glam", price: 180, duration: 75 },
    ],
  },
  {
    id: "nails",
    category: "Nails",
    description: "Precision nail artistry with premium, long-lasting formulas.",
    icon: "◆",
    items: [
      { name: "Signature Gel Set", price: 85, duration: 75 },
      { name: "Nail Art Design", price: 120, duration: 90 },
      { name: "Mani & Pedi", price: 100, duration: 100 },
      { name: "Acrylic Extensions", price: 140, duration: 120 },
    ],
  },
  {
    id: "lashes",
    category: "Eyelashes",
    description: "Volume, length, and definition. Eyes that speak before you do.",
    icon: "◇",
    items: [
      { name: "Classic Full Set", price: 180, duration: 120 },
      { name: "Volume Full Set", price: 220, duration: 150 },
      { name: "Hybrid Set", price: 200, duration: 135 },
      { name: "Lash Lift & Tint", price: 110, duration: 75 },
    ],
  },
  {
    id: "facials",
    category: "Facials",
    description: "Clinical-grade treatments meeting luxury spa experience.",
    icon: "○",
    items: [
      { name: "Signature Facial", price: 190, duration: 90 },
      { name: "Glow Infusion", price: 240, duration: 75 },
      { name: "Anti-Aging Ritual", price: 280, duration: 90 },
      { name: "Deep Cleanse", price: 160, duration: 60 },
    ],
  },
  {
    id: "hair",
    category: "Hair",
    description: "Transformative hair services from precision cuts to colour artistry.",
    icon: "〜",
    items: [
      { name: "Precision Cut", price: 95, duration: 60 },
      { name: "Balayage", price: 280, duration: 180 },
      { name: "Keratin Treatment", price: 350, duration: 240 },
      { name: "Blowout & Style", price: 75, duration: 60 },
    ],
  },
  {
    id: "spa",
    category: "Spa & Body",
    description: "Full-body rituals designed to restore, rejuvenate, and renew.",
    icon: "◉",
    items: [
      { name: "Full Body Massage", price: 160, duration: 90 },
      { name: "Body Polish", price: 140, duration: 75 },
      { name: "Hot Stone Ritual", price: 200, duration: 90 },
      { name: "Aromatherapy Wrap", price: 180, duration: 90 },
    ],
  },
];

export const staff = [
  {
    id: "s1",
    name: "Amara Osei",
    role: "Lead Makeup Artist",
    specialties: ["Bridal", "Editorial", "Special FX"],
    rating: 4.9,
    reviews: 247,
    gradient: "from-rose-900/50 to-amber-900/50",
  },
  {
    id: "s2",
    name: "Lydia Chen",
    role: "Senior Nail Technician",
    specialties: ["Nail Art", "Gel Extensions", "3D Design"],
    rating: 4.8,
    reviews: 189,
    gradient: "from-pink-900/50 to-purple-900/50",
  },
  {
    id: "s3",
    name: "Nia Abara",
    role: "Lash & Brow Specialist",
    specialties: ["Volume Lashes", "Microblading", "Lash Lift"],
    rating: 5.0,
    reviews: 312,
    gradient: "from-amber-900/50 to-rose-900/50",
  },
  {
    id: "s4",
    name: "Sofia Delacroix",
    role: "Skin Therapist",
    specialties: ["Anti-Aging", "Acne Care", "LED Therapy"],
    rating: 4.9,
    reviews: 203,
    gradient: "from-purple-900/50 to-pink-900/50",
  },
  {
    id: "s5",
    name: "Kezia Williams",
    role: "Master Colorist",
    specialties: ["Balayage", "Colour Correction", "Vivid"],
    rating: 4.7,
    reviews: 178,
    gradient: "from-orange-900/50 to-red-900/50",
  },
  {
    id: "s6",
    name: "Priya Menon",
    role: "Spa Therapist",
    specialties: ["Hot Stone", "Aromatherapy", "Body Rituals"],
    rating: 4.8,
    reviews: 156,
    gradient: "from-teal-900/50 to-cyan-900/50",
  },
];

export const products = [
  {
    id: "p1",
    name: "Velvet Rose Face Oil",
    category: "Skincare",
    price: 89,
    originalPrice: 120,
    badge: "Best Seller",
    description: "Luxurious rose hip & bakuchiol facial oil for radiant, youthful skin.",
    gradient: "from-rose-950 to-pink-900",
    accent: "#D4A8A8",
  },
  {
    id: "p2",
    name: "Noir Matte Lipstick",
    category: "Makeup",
    price: 42,
    badge: "New",
    description: "Velvety matte finish in 12 exclusive shades.",
    gradient: "from-stone-950 to-neutral-900",
    accent: "#C9A55A",
  },
  {
    id: "p3",
    name: "Gold Elixir Serum",
    category: "Skincare",
    price: 145,
    badge: "Premium",
    description: "24K gold-infused serum for unparalleled luminosity.",
    gradient: "from-amber-950 to-yellow-900",
    accent: "#C9A55A",
  },
  {
    id: "p4",
    name: "Lash Amplifier Mascara",
    category: "Makeup",
    price: 38,
    description: "Dramatic volume and length for show-stopping lashes.",
    gradient: "from-slate-950 to-zinc-900",
    accent: "#D4A8A8",
  },
  {
    id: "p5",
    name: "Hydra-Glow Moisturiser",
    category: "Skincare",
    price: 78,
    badge: "Trending",
    description: "72-hour hydration with hyaluronic acid and ceramides.",
    gradient: "from-blue-950 to-indigo-900",
    accent: "#B57850",
  },
  {
    id: "p6",
    name: "Brow Sculpt Kit",
    category: "Makeup",
    price: 55,
    description: "Complete brow shaping with pomade, pencil, and gel.",
    gradient: "from-purple-950 to-violet-900",
    accent: "#E8C99A",
  },
  {
    id: "p7",
    name: "Rose Gold Lip Set",
    category: "Makeup",
    price: 65,
    badge: "Limited",
    description: "Curated lip collection in rose-tinted metallics.",
    gradient: "from-rose-950 to-amber-900",
    accent: "#B57850",
  },
  {
    id: "p8",
    name: "Midnight Repair Mask",
    category: "Skincare",
    price: 95,
    description: "Overnight restorative mask with retinol and peptides.",
    gradient: "from-gray-950 to-slate-900",
    accent: "#C9A55A",
  },
];

export const testimonials = [
  {
    id: "t1",
    name: "Isabelle Laurent",
    service: "Bridal Makeup",
    artist: "Amara Osei",
    rating: 5,
    text: "Pokaliz Laire turned my wedding day into a dream I never wanted to wake from. Amara understood my vision perfectly — she didn't just do my makeup, she elevated me.",
    location: "London",
    date: "March 2025",
  },
  {
    id: "t2",
    name: "Zanele Dlamini",
    service: "Volume Lash Set",
    artist: "Nia Abara",
    rating: 5,
    text: "I've been to countless lash salons but nothing comes close to the artistry here. Nia is a genius. My lashes last six weeks and still look absolutely flawless.",
    location: "Lagos",
    date: "April 2025",
  },
  {
    id: "t3",
    name: "Camille Fontaine",
    service: "Anti-Aging Facial",
    artist: "Sofia Delacroix",
    rating: 5,
    text: "The glow after my session was unlike anything I'd experienced. Sofia is incredibly knowledgeable. I walked out looking five years younger and feeling a hundred times more confident.",
    location: "Paris",
    date: "February 2025",
  },
  {
    id: "t4",
    name: "Reena Kapoor",
    service: "Balayage",
    artist: "Kezia Williams",
    rating: 5,
    text: "I'd been nervous about colour after a bad experience elsewhere. Kezia took her time understanding exactly what I wanted. The result was breathtaking — worth every single penny.",
    location: "Dubai",
    date: "April 2025",
  },
  {
    id: "t5",
    name: "Naomi Asante",
    service: "Hot Stone Ritual",
    artist: "Priya Menon",
    rating: 5,
    text: "Walking into Pokaliz Laire feels like entering another world entirely. The hot stone ritual left me in a state of bliss I carried for days. I'll never go anywhere else.",
    location: "Accra",
    date: "March 2025",
  },
];

export const memberships = [
  {
    id: "m1",
    name: "Soirée",
    price: 89,
    period: "month",
    description: "For the woman who deserves a little luxury every month.",
    features: [
      "1 Express Facial per month",
      "15% off all services",
      "10% off all products",
      "Priority booking window",
      "Monthly beauty gift",
    ],
    accent: "#887A90",
    featured: false,
    cta: "Begin Soirée",
  },
  {
    id: "m2",
    name: "Lumière",
    price: 199,
    period: "month",
    description: "Our most loved tier. Complete beauty, every month.",
    features: [
      "1 Signature Facial per month",
      "1 Nail Treatment per month",
      "20% off all services",
      "15% off all products",
      "Priority + same-day booking",
      "Quarterly luxury gift box",
      "Dedicated beauty advisor",
    ],
    accent: "#C9A55A",
    featured: true,
    cta: "Join Lumière",
  },
  {
    id: "m3",
    name: "Couture",
    price: 399,
    period: "month",
    description: "The pinnacle of personalised beauty care.",
    features: [
      "Unlimited express treatments",
      "2 Premium services per month",
      "25% off all services",
      "20% off all products",
      "VIP concierge booking",
      "Monthly luxury gift box",
      "Annual beauty retreat invitation",
      "Personal stylist access",
    ],
    accent: "#B57850",
    featured: false,
    cta: "Go Couture",
  },
];

export const timeSlots = [
  "9:00 AM", "9:30 AM", "10:00 AM", "10:30 AM",
  "11:00 AM", "11:30 AM", "12:00 PM", "12:30 PM",
  "1:00 PM", "2:00 PM", "2:30 PM", "3:00 PM",
  "3:30 PM", "4:00 PM", "4:30 PM", "5:00 PM",
];

export const socialPosts = [
  { id: "sp1", type: "video", gradient: "from-rose-900 to-pink-800", caption: "Bridal glow transformation", likes: "12.4K", tag: "#BridalGlow" },
  { id: "sp2", type: "image", gradient: "from-amber-900 to-orange-800", caption: "Velvet matte lips", likes: "8.7K", tag: "#VelvetLips" },
  { id: "sp3", type: "video", gradient: "from-purple-900 to-violet-800", caption: "Volume lash magic", likes: "15.2K", tag: "#LashGoals" },
  { id: "sp4", type: "image", gradient: "from-slate-900 to-zinc-800", caption: "Nail art editorial", likes: "6.9K", tag: "#NailArt" },
  { id: "sp5", type: "image", gradient: "from-teal-900 to-cyan-800", caption: "Skin glow ritual", likes: "9.3K", tag: "#SkinGlow" },
  { id: "sp6", type: "video", gradient: "from-red-900 to-rose-800", caption: "Balayage dreams", likes: "11.1K", tag: "#Balayage" },
];

export const bookingDates = [
  { day: "Mon", date: 12, available: true },
  { day: "Tue", date: 13, available: true },
  { day: "Wed", date: 14, available: false },
  { day: "Thu", date: 15, available: true },
  { day: "Fri", date: 16, available: true },
  { day: "Sat", date: 17, available: true },
  { day: "Sun", date: 18, available: false },
  { day: "Mon", date: 19, available: true },
  { day: "Tue", date: 20, available: true },
  { day: "Wed", date: 21, available: true },
  { day: "Thu", date: 22, available: false },
  { day: "Fri", date: 23, available: true },
  { day: "Sat", date: 24, available: true },
  { day: "Sun", date: 25, available: false },
];
